apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vxlan-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-vxlan-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kube-vxlan-controller
    namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-vxlan-controller
  namespace: kube-system
data:
  vxeth0: "100"
  vxeth1: "101"
  vxeth2: "102"
  vxeth3: "103"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-vxlan-controller-config
  namespace: kube-system
data:
  config: |
    [{'kube-vxlan-controller', [
       {selector, "vxlan"},
       {annotation, "vxlan.travelping.com/names"}
    ]}].
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: kube-vxlan-controller
  name: kube-vxlan-controller
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        run: kube-vxlan-controller
    spec:
      containers:
      - name: kube-vxlan-controller
        image: aialferov/kube-vxlan-controller:latest
        args:
        - run
        - --selector=vxlan=true
        - --annotation=vxlan.travelping.com/names
        volumeMounts:
        - name: kube-vxlan-controller
          mountPath: /etc/kube-vxlan-controller
      volumes:
      - name: kube-vxlan-controller
        configMap:
          name: kube-vxlan-controller-config
      serviceAccount: kube-vxlan-controller
      serviceAccountName: kube-vxlan-controller
