apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: a
spec:
  template:
    metadata:
      labels:
        run: a
        vxlan.travelping.com: "true"
      annotations:
        vxlan.travelping.com/networks: |
          vxeth1
            up
            ip=192.168.11.2/29
            route=192.168.12.0/29:192.168.11.1
    spec:
      initContainers:
      - image: aialferov/kube-vxlan-controller-agent
        name: vxlan-controller-agent-init
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      containers:
      - image: aialferov/pause
        imagePullPolicy: Always
        name: a
      - image: aialferov/kube-vxlan-controller-agent
        name: vxlan-controller-agent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: b
spec:
  template:
    metadata:
      labels:
        run: b
        vxlan.travelping.com: "true"
      annotations:
        vxlan.travelping.com/networks: |
          vxeth2
            up
            ip=192.168.12.2/29
            route=192.168.11.0/29:192.168.12.1
    spec:
      initContainers:
      - image: aialferov/kube-vxlan-controller-agent
        name: vxlan-controller-agent-init
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      containers:
      - image: aialferov/pause
        imagePullPolicy: Always
        name: b
      - image: aialferov/kube-vxlan-controller-agent
        name: vxlan-controller-agent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gw
spec:
  template:
    metadata:
      labels:
        run: gw
        vxlan.travelping.com: "true"
      annotations:
        vxlan.travelping.com/networks: |
          vxeth1 up ip=192.168.11.1/29
          vxeth2 up ip=192.168.12.1/29
    spec:
      initContainers:
      - image: aialferov/kube-vxlan-controller-agent
        name: vxlan-controller-agent-init
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      containers:
      - image: aialferov/pause
        imagePullPolicy: Always
        name: gw
      - image: aialferov/kube-vxlan-controller-agent
        name: vxlan-controller-agent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
